name: Slack App Deployment

on:
  push:
    branches: [ main ]

# jobs:
#     notify-tydo-klaviyo-update:
#         name: "Notify Tydo about Klaviyo Connector Update"
#         runs-on: ubuntu-latest
#         #needs:
#             #- publish_connectors
#         #if: |
#         #    success() && 
#         #    (contains(github.event.head_commit.modified, 'airbyte-integrations/connectors/source-klaviyo/metadata.yaml') || 
#         #    github.event.inputs.connectors-options == '--name=source-klaviyo')
#         steps:
#             - name: Send Tydo notification about Klaviyo connector update
#             - id: tydo-slack
#             - uses: slackapi/slack-github-action@v2.0.0
#             - with:
#                 payload: |
#                 {
#                     "text": "🔔 *New Klaviyo Connector Version Available*\n\nA new version of the Airbyte Klaviyo source connector has been published.\n\nDetails:\n• Published by: ${{ github.actor }}\n• Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n• Date: ${{ format(github.event.head_commit.timestamp || github.event.repository.updated_at, 'MMMM DD, YYYY') }}"
#                 }
#             - env:
#                 #SLACK_WEBHOOK_URL: ${{ secrets.TYDO_EXTERNAL_WEBHOOK }}
#                 SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SERVICE_TOKEN }}

# jobs:
#   slack-notifications:
#     runs-on: ubuntu-20.04
#     name: Sends a message to Slack when a push, a pull request or an issue is made
#     steps:
#       - name: Send message to Slack API
#         uses: archive/github-actions-slack@v2.0.0
#         id: notify
#         with:
#         #   slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
#         #   slack-channel: CPPUV5KU0
#           slack-text: "Hello! Event New Klaviyo Connector ...."
#           webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
#         # env: 
#         #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} 

# jobs:
#   run:
#     name: Share a travel review to channel
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repo
#         uses: actions/checkout@v4
#         with:
#           persist-credentials: false

#       - name: Forward a saved message
#         uses: slackapi/slack-github-action@v2.0.0
#         with:
#           payload: "Hi"
#           payload-templated: true
#           webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
#           webhook-type: incoming-webhook
#         env:
#           SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}


jobs:
  run:
    name: Share a travel review to channel
    runs-on: ubuntu-latest
    steps:
        -   name: Post a message in a channel
            uses: slackapi/slack-github-action@v2.0.0
            with:
                # webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
                webhook: https://hooks.slack.com/services/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
                webhook-type: incoming-webhook
                payload: |
                    # text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                    text: "Post to slack channel"